### ISSUE TITLE
I got a test error while doing a clean yarn/npm install when cloning the repo

### ISSUE THREAD

**Issue by miltiadis** [dwyl/javascript-todo-list-tutorial#29] opened 2020-08-10 23:43 UTC
Hi, I got that error and the tests failed afterwards when I did a clean install. I'm using macOS Catalina 10.15.5. 
```
 ✖ <input autofocus> is "activeElement"
      operator: equal
      expected: |-
        <body>...</body>
      actual: |-
        <input class="new-todo" autofocus="" id="new"></input>
      at: Test.<anonymous> (/Users/miltiadisbouchalakis/projects/todo-mvc/javascript-todo-list-tutorial/test/elmish.test.js:60:5)
      stack: |-
```
![image](https://user-images.githubusercontent.com/3041938/89841720-9f5edf80-db6b-11ea-9ece-6f61e7066dd9.png)

My temp solution was to comment that test but I'm not sure how to fix it since I just started checking this project.

Thanks,
M

**Comment by nelsonic** [comment] 2020-08-11 00:09
Hi @miltiadis thanks for opening this issue to share your experience. 👍 
It's very strange that one of the tests would fail when none of the `devDependencies` has diverged.
Can you:
a. try using `npm test` instead of `yarn`
b. let us know what OS and version of Node.js you are using.

**Comment by nelsonic** [comment] 2020-08-11 00:12
Scratch that! I just did a fresh install and got the _same_ error! 🤦 

![image](https://user-images.githubusercontent.com/194400/89843162-996afd80-db6f-11ea-8892-d5218eaba1dd.png)

Going to check it out _now_!

**Comment by miltiadis** [comment] 2020-08-11 00:14
Ah, no worries!

I'm glad we spotted it early.

Thanks for trying to help.

**Comment by nelsonic** [comment] 2020-08-11 00:34
Ok, so it looks like the test is expecting `<input class="new-todo" autofocus= ...>` 
but the actual result is: `<body> ... </body>` i.e. the full `<body>` of the DOM.

the `document.activeElement` is actually `HTMLBodyElement {}` ... 😕

**Comment by nelsonic** [comment] 2020-08-11 00:38
Ok, I've tracked it down. `JSDOM` has introduced a breaking change! 🤦 
If you change the line in you` package.json` 

from:

https://github.com/dwyl/javascript-todo-list-tutorial/blob/e6736add9df1f46035f8a9d1dbdc14c71a7cdb41/package.json#L14

to:

```json
    "jsdom": "16.0.1",
```
i.e. you set the version of `jsdom` to be _fixed_ not a "greater than".
then the tests all pass again.

**Comment by miltiadis** [comment] 2020-08-11 00:44
Thanks for the ultra-fast solution 👍  
I just locked the version to the one you mentioned and it works for me as well.

Shall I close this issue

**Comment by nelsonic** [comment] 2020-08-11 00:53
@miltiadis sadly, we cannot close the issue unless we apply the "fix" to `master`.
But we prefer to actually _fix_ the issue permanently rather than just pin the version of `jsdom`.
The `jsdom` changelog https://github.com/jsdom/jsdom/blob/master/Changelog.md says `v16.4.0` "fixed" `el.focus()` ...
But in reality they have diverged the expected behaviour ... 🙄

**Comment by nelsonic** [comment] 2020-08-11 23:18
Known issue: https://github.com/jsdom/jsdom/issues/2586#issuecomment-627155416 ... 🤦 
This is very much an issue with JSDOM not with our test or how our ("elmish") microframework works. 🤷‍♂️

**Comment by nelsonic** [comment] 2023-08-05 06:01
No longer an issue. Fresh `git clone`, `npm install` & `npm test`:

```sh
    root HTMLDivElement {}
    JSDOM window.location.href: about:blank
    START window.location.hash:  (empty string)
    START window.history.length: 1
    UPDATED window.history.length: 2
    UPDATED state: { hash: '#/active' }
    UPDATED window.location.hash: #/active
    value: Let's solve our own problem
    value: Let's solve our own problem
    value: Let's solve our own problem
    value: Let's solve our own problem
    value: Let's solve our own problem
    -------------|---------|----------|---------|---------|-------------------
    File         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
    -------------|---------|----------|---------|---------|-------------------
    All files    |     100 |      100 |     100 |     100 |
     elmish.js   |     100 |      100 |     100 |     100 |
     todo-app.js |     100 |      100 |     100 |     100 |
    -------------|---------|----------|---------|---------|-------------------

  total:     137
  passing:   137

  duration:  1.4s
```

**Closed by nelsonic** 2023-08-05 06:01 UTC
